import { createContext, useContext, useState } from "react";

export type TimezoneSetting = {
  id: string;
  label: string;
  city: string;
  country: string;
  region: TimezoneRegion;
  timeZone: string;
  utcOffset: string;
  utcOffsetMinutes?: number;
  usesAutoTimezone?: boolean;
  latitude: number;
  longitude: number;
};

export type TimezoneRegion =
  | "UTC"
  | "Oceania"
  | "Asia"
  | "Middle East"
  | "Africa"
  | "Europe"
  | "North America"
  | "Central America"
  | "South America";

export const timezoneRegions: TimezoneRegion[] = [
  "UTC",
  "Oceania",
  "Asia",
  "Middle East",
  "Africa",
  "Europe",
  "North America",
  "Central America",
  "South America",
];

export const timezoneOptions: TimezoneSetting[] = [
  {
    id: "utc",
    label: "UTC",
    city: "UTC",
    country: "Coordinated Universal Time",
    region: "UTC",
    timeZone: "UTC",
    utcOffset: "UTC+00:00",
    latitude: 0,
    longitude: 0,
  },
  {
    id: "sydney",
    label: "Sydney",
    city: "Sydney",
    country: "Australia",
    region: "Oceania",
    timeZone: "Australia/Sydney",
    utcOffset: "UTC+10:00/+11:00",
    latitude: -33.75,
    longitude: 151.15,
  },
  {
    id: "perth",
    label: "Perth",
    city: "Perth",
    country: "Australia",
    region: "Oceania",
    timeZone: "Australia/Perth",
    utcOffset: "UTC+08:00",
    latitude: -31.95,
    longitude: 115.86,
  },
  {
    id: "melbourne",
    label: "Melbourne",
    city: "Melbourne",
    country: "Australia",
    region: "Oceania",
    timeZone: "Australia/Melbourne",
    utcOffset: "UTC+10:00/+11:00",
    latitude: -37.81,
    longitude: 144.96,
  },
  {
    id: "brisbane",
    label: "Brisbane",
    city: "Brisbane",
    country: "Australia",
    region: "Oceania",
    timeZone: "Australia/Brisbane",
    utcOffset: "UTC+10:00",
    latitude: -27.47,
    longitude: 153.03,
  },
  {
    id: "adelaide",
    label: "Adelaide",
    city: "Adelaide",
    country: "Australia",
    region: "Oceania",
    timeZone: "Australia/Adelaide",
    utcOffset: "UTC+09:30/+10:30",
    latitude: -34.93,
    longitude: 138.6,
  },
  {
    id: "darwin",
    label: "Darwin",
    city: "Darwin",
    country: "Australia",
    region: "Oceania",
    timeZone: "Australia/Darwin",
    utcOffset: "UTC+09:30",
    latitude: -12.46,
    longitude: 130.84,
  },
  {
    id: "hobart",
    label: "Hobart",
    city: "Hobart",
    country: "Australia",
    region: "Oceania",
    timeZone: "Australia/Hobart",
    utcOffset: "UTC+10:00/+11:00",
    latitude: -42.88,
    longitude: 147.33,
  },
  {
    id: "canberra",
    label: "Canberra",
    city: "Canberra",
    country: "Australia",
    region: "Oceania",
    timeZone: "Australia/Sydney",
    utcOffset: "UTC+10:00/+11:00",
    latitude: -35.28,
    longitude: 149.13,
  },
  {
    id: "auckland",
    label: "Auckland",
    city: "Auckland",
    country: "New Zealand",
    region: "Oceania",
    timeZone: "Pacific/Auckland",
    utcOffset: "UTC+12:00/+13:00",
    latitude: -36.85,
    longitude: 174.76,
  },
  {
    id: "wellington",
    label: "Wellington",
    city: "Wellington",
    country: "New Zealand",
    region: "Oceania",
    timeZone: "Pacific/Auckland",
    utcOffset: "UTC+12:00/+13:00",
    latitude: -41.29,
    longitude: 174.78,
  },
  {
    id: "christchurch",
    label: "Christchurch",
    city: "Christchurch",
    country: "New Zealand",
    region: "Oceania",
    timeZone: "Pacific/Auckland",
    utcOffset: "UTC+12:00/+13:00",
    latitude: -43.53,
    longitude: 172.63,
  },
  {
    id: "queenstown",
    label: "Queenstown",
    city: "Queenstown",
    country: "New Zealand",
    region: "Oceania",
    timeZone: "Pacific/Auckland",
    utcOffset: "UTC+12:00/+13:00",
    latitude: -45.03,
    longitude: 168.66,
  },
  {
    id: "tokyo",
    label: "Tokyo",
    city: "Tokyo",
    country: "Japan",
    region: "Asia",
    timeZone: "Asia/Tokyo",
    utcOffset: "UTC+09:00",
    latitude: 35.68,
    longitude: 139.76,
  },
  {
    id: "singapore",
    label: "Singapore",
    city: "Singapore",
    country: "Singapore",
    region: "Asia",
    timeZone: "Asia/Singapore",
    utcOffset: "UTC+08:00",
    latitude: 1.35,
    longitude: 103.82,
  },
  {
    id: "hong-kong",
    label: "Hong Kong",
    city: "Hong Kong",
    country: "Hong Kong",
    region: "Asia",
    timeZone: "Asia/Hong_Kong",
    utcOffset: "UTC+08:00",
    latitude: 22.32,
    longitude: 114.17,
  },
  {
    id: "seoul",
    label: "Seoul",
    city: "Seoul",
    country: "South Korea",
    region: "Asia",
    timeZone: "Asia/Seoul",
    utcOffset: "UTC+09:00",
    latitude: 37.57,
    longitude: 126.98,
  },
  {
    id: "delhi",
    label: "Delhi",
    city: "Delhi",
    country: "India",
    region: "Asia",
    timeZone: "Asia/Kolkata",
    utcOffset: "UTC+05:30",
    latitude: 28.61,
    longitude: 77.21,
  },
  {
    id: "dubai",
    label: "Dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    timeZone: "Asia/Dubai",
    utcOffset: "UTC+04:00",
    latitude: 25.2,
    longitude: 55.27,
  },
  {
    id: "jerusalem",
    label: "Jerusalem",
    city: "Jerusalem",
    country: "Israel",
    region: "Middle East",
    timeZone: "Asia/Jerusalem",
    utcOffset: "UTC+02:00/+03:00",
    latitude: 31.77,
    longitude: 35.21,
  },
  {
    id: "tel-aviv",
    label: "Tel Aviv",
    city: "Tel Aviv",
    country: "Israel",
    region: "Middle East",
    timeZone: "Asia/Jerusalem",
    utcOffset: "UTC+02:00/+03:00",
    latitude: 32.08,
    longitude: 34.78,
  },
  {
    id: "riyadh",
    label: "Riyadh",
    city: "Riyadh",
    country: "Saudi Arabia",
    region: "Middle East",
    timeZone: "Asia/Riyadh",
    utcOffset: "UTC+03:00",
    latitude: 24.71,
    longitude: 46.68,
  },
  {
    id: "cairo",
    label: "Cairo",
    city: "Cairo",
    country: "Egypt",
    region: "Africa",
    timeZone: "Africa/Cairo",
    utcOffset: "UTC+02:00/+03:00",
    latitude: 30.04,
    longitude: 31.24,
  },
  {
    id: "johannesburg",
    label: "Johannesburg",
    city: "Johannesburg",
    country: "South Africa",
    region: "Africa",
    timeZone: "Africa/Johannesburg",
    utcOffset: "UTC+02:00",
    latitude: -26.2,
    longitude: 28.04,
  },
  {
    id: "nairobi",
    label: "Nairobi",
    city: "Nairobi",
    country: "Kenya",
    region: "Africa",
    timeZone: "Africa/Nairobi",
    utcOffset: "UTC+03:00",
    latitude: -1.29,
    longitude: 36.82,
  },
  {
    id: "london",
    label: "London",
    city: "London",
    country: "United Kingdom",
    region: "Europe",
    timeZone: "Europe/London",
    utcOffset: "UTC+00:00/+01:00",
    latitude: 51.51,
    longitude: -0.13,
  },
  {
    id: "paris",
    label: "Paris",
    city: "Paris",
    country: "France",
    region: "Europe",
    timeZone: "Europe/Paris",
    utcOffset: "UTC+01:00/+02:00",
    latitude: 48.86,
    longitude: 2.35,
  },
  {
    id: "berlin",
    label: "Berlin",
    city: "Berlin",
    country: "Germany",
    region: "Europe",
    timeZone: "Europe/Berlin",
    utcOffset: "UTC+01:00/+02:00",
    latitude: 52.52,
    longitude: 13.41,
  },
  {
    id: "moscow",
    label: "Moscow",
    city: "Moscow",
    country: "Russia",
    region: "Europe",
    timeZone: "Europe/Moscow",
    utcOffset: "UTC+03:00",
    latitude: 55.76,
    longitude: 37.62,
  },
  {
    id: "rome",
    label: "Rome",
    city: "Rome",
    country: "Italy",
    region: "Europe",
    timeZone: "Europe/Rome",
    utcOffset: "UTC+01:00/+02:00",
    latitude: 41.9,
    longitude: 12.5,
  },
  {
    id: "madrid",
    label: "Madrid",
    city: "Madrid",
    country: "Spain",
    region: "Europe",
    timeZone: "Europe/Madrid",
    utcOffset: "UTC+01:00/+02:00",
    latitude: 40.42,
    longitude: -3.7,
  },
  {
    id: "amsterdam",
    label: "Amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    region: "Europe",
    timeZone: "Europe/Amsterdam",
    utcOffset: "UTC+01:00/+02:00",
    latitude: 52.37,
    longitude: 4.9,
  },
  {
    id: "stockholm",
    label: "Stockholm",
    city: "Stockholm",
    country: "Sweden",
    region: "Europe",
    timeZone: "Europe/Stockholm",
    utcOffset: "UTC+01:00/+02:00",
    latitude: 59.33,
    longitude: 18.07,
  },
  {
    id: "dublin",
    label: "Dublin",
    city: "Dublin",
    country: "Ireland",
    region: "Europe",
    timeZone: "Europe/Dublin",
    utcOffset: "UTC+00:00/+01:00",
    latitude: 53.35,
    longitude: -6.26,
  },
  {
    id: "vienna",
    label: "Vienna",
    city: "Vienna",
    country: "Austria",
    region: "Europe",
    timeZone: "Europe/Vienna",
    utcOffset: "UTC+01:00/+02:00",
    latitude: 48.21,
    longitude: 16.37,
  },
  {
    id: "zurich",
    label: "Zurich",
    city: "Zurich",
    country: "Switzerland",
    region: "Europe",
    timeZone: "Europe/Zurich",
    utcOffset: "UTC+01:00/+02:00",
    latitude: 47.38,
    longitude: 8.54,
  },
  {
    id: "athens",
    label: "Athens",
    city: "Athens",
    country: "Greece",
    region: "Europe",
    timeZone: "Europe/Athens",
    utcOffset: "UTC+02:00/+03:00",
    latitude: 37.98,
    longitude: 23.73,
  },
  {
    id: "warsaw",
    label: "Warsaw",
    city: "Warsaw",
    country: "Poland",
    region: "Europe",
    timeZone: "Europe/Warsaw",
    utcOffset: "UTC+01:00/+02:00",
    latitude: 52.23,
    longitude: 21.01,
  },
  {
    id: "prague",
    label: "Prague",
    city: "Prague",
    country: "Czechia",
    region: "Europe",
    timeZone: "Europe/Prague",
    utcOffset: "UTC+01:00/+02:00",
    latitude: 50.08,
    longitude: 14.44,
  },
  {
    id: "new-york",
    label: "New York",
    city: "New York",
    country: "United States",
    region: "North America",
    timeZone: "America/New_York",
    utcOffset: "UTC-05:00/-04:00",
    latitude: 40.71,
    longitude: -74.01,
  },
  {
    id: "los-angeles",
    label: "Los Angeles",
    city: "Los Angeles",
    country: "United States",
    region: "North America",
    timeZone: "America/Los_Angeles",
    utcOffset: "UTC-08:00/-07:00",
    latitude: 34.05,
    longitude: -118.24,
  },
  {
    id: "toronto",
    label: "Toronto",
    city: "Toronto",
    country: "Canada",
    region: "North America",
    timeZone: "America/Toronto",
    utcOffset: "UTC-05:00/-04:00",
    latitude: 43.65,
    longitude: -79.38,
  },
  {
    id: "chicago",
    label: "Chicago",
    city: "Chicago",
    country: "United States",
    region: "North America",
    timeZone: "America/Chicago",
    utcOffset: "UTC-06:00/-05:00",
    latitude: 41.88,
    longitude: -87.63,
  },
  {
    id: "denver",
    label: "Denver",
    city: "Denver",
    country: "United States",
    region: "North America",
    timeZone: "America/Denver",
    utcOffset: "UTC-07:00/-06:00",
    latitude: 39.74,
    longitude: -104.99,
  },
  {
    id: "phoenix",
    label: "Phoenix",
    city: "Phoenix",
    country: "United States",
    region: "North America",
    timeZone: "America/Phoenix",
    utcOffset: "UTC-07:00",
    latitude: 33.45,
    longitude: -112.07,
  },
  {
    id: "seattle",
    label: "Seattle",
    city: "Seattle",
    country: "United States",
    region: "North America",
    timeZone: "America/Los_Angeles",
    utcOffset: "UTC-08:00/-07:00",
    latitude: 47.61,
    longitude: -122.33,
  },
  {
    id: "vancouver",
    label: "Vancouver",
    city: "Vancouver",
    country: "Canada",
    region: "North America",
    timeZone: "America/Vancouver",
    utcOffset: "UTC-08:00/-07:00",
    latitude: 49.28,
    longitude: -123.12,
  },
  {
    id: "montreal",
    label: "Montreal",
    city: "Montreal",
    country: "Canada",
    region: "North America",
    timeZone: "America/Toronto",
    utcOffset: "UTC-05:00/-04:00",
    latitude: 45.5,
    longitude: -73.57,
  },
  {
    id: "calgary",
    label: "Calgary",
    city: "Calgary",
    country: "Canada",
    region: "North America",
    timeZone: "America/Edmonton",
    utcOffset: "UTC-07:00/-06:00",
    latitude: 51.05,
    longitude: -114.07,
  },
  {
    id: "mexico-city",
    label: "Mexico City",
    city: "Mexico City",
    country: "Mexico",
    region: "Central America",
    timeZone: "America/Mexico_City",
    utcOffset: "UTC-06:00",
    latitude: 19.43,
    longitude: -99.13,
  },
  {
    id: "panama-city",
    label: "Panama City",
    city: "Panama City",
    country: "Panama",
    region: "Central America",
    timeZone: "America/Panama",
    utcOffset: "UTC-05:00",
    latitude: 8.98,
    longitude: -79.52,
  },
  {
    id: "sao-paulo",
    label: "São Paulo",
    city: "São Paulo",
    country: "Brazil",
    region: "South America",
    timeZone: "America/Sao_Paulo",
    utcOffset: "UTC-03:00",
    latitude: -23.55,
    longitude: -46.63,
  },
  {
    id: "buenos-aires",
    label: "Buenos Aires",
    city: "Buenos Aires",
    country: "Argentina",
    region: "South America",
    timeZone: "America/Argentina/Buenos_Aires",
    utcOffset: "UTC-03:00",
    latitude: -34.61,
    longitude: -58.38,
  },
  {
    id: "lima",
    label: "Lima",
    city: "Lima",
    country: "Peru",
    region: "South America",
    timeZone: "America/Lima",
    utcOffset: "UTC-05:00",
    latitude: -12.05,
    longitude: -77.04,
  },
];

type AppSettings = {
  isNightMode: boolean;
  setIsNightMode: (value: boolean) => void;
  blurProfilePhoto: boolean;
  setBlurProfilePhoto: (value: boolean) => void;
  largerText: boolean;
  setLargerText: (value: boolean) => void;
  highContrast: boolean;
  setHighContrast: (value: boolean) => void;
  reduceMotion: boolean;
  setReduceMotion: (value: boolean) => void;
  screenReaderHints: boolean;
  setScreenReaderHints: (value: boolean) => void;
  appLanguage: string;
  setAppLanguage: (value: string) => void;
  translationLanguage: string;
  setTranslationLanguage: (value: string) => void;
  timezone: TimezoneSetting;
  setTimezone: (value: TimezoneSetting) => void;
};

const AppSettingsContext = createContext<AppSettings | null>(null);

export function AppSettingsProvider({ children }: { children: React.ReactNode }) {
  const [isNightMode, setIsNightMode] = useState(false);
  const [blurProfilePhoto, setBlurProfilePhoto] = useState(true);
  const [largerText, setLargerText] = useState(false);
  const [highContrast, setHighContrast] = useState(false);
  const [reduceMotion, setReduceMotion] = useState(false);
  const [screenReaderHints, setScreenReaderHints] = useState(true);
  const [appLanguage, setAppLanguage] = useState("English");
  const [translationLanguage, setTranslationLanguage] = useState("English");
  const [timezone, setTimezone] = useState<TimezoneSetting>(timezoneOptions[0]);

  return (
    <AppSettingsContext.Provider
      value={{
        isNightMode,
        setIsNightMode,
        blurProfilePhoto,
        setBlurProfilePhoto,
        largerText,
        setLargerText,
        highContrast,
        setHighContrast,
        reduceMotion,
        setReduceMotion,
        screenReaderHints,
        setScreenReaderHints,
        appLanguage,
        setAppLanguage,
        translationLanguage,
        setTranslationLanguage,
        timezone,
        setTimezone,
      }}
    >
      {children}
    </AppSettingsContext.Provider>
  );
}

export function useAppSettings() {
  const context = useContext(AppSettingsContext);

  if (!context) {
    throw new Error("useAppSettings must be used inside AppSettingsProvider");
  }

  return context;
}
