export const englishEventCreationCopy = {
  title: "My Events",
  subtitle: "Draft local meetup ideas at a pace that feels clear and manageable.",
  createEvent: "Create a Meetup",
  emptyTitle: "No events created yet",
  emptyCopy: "Start with a simple coffee, movie, board game, walk, study session, or another low-pressure idea.",
  sheetTitle: "Create a Meetup",
  sheetSubtitle: "Set a clear plan, place, and tone.",
  eventName: "Event name",
  eventNamePlaceholder: "Board games and coffee",
  date: "Date",
  datePlaceholder: "24 May",
  time: "Time",
  timePlaceholder: "6:30pm",
  venue: "Venue",
  venuePlaceholder: "Chatswood Social Cafe",
  backupVenue: "Bad weather backup",
  backupVenuePlaceholder: "Indoor table at nearby cafe",
  noiseLevel: "Noise level",
  address: "Address",
  addressPlaceholder: "Enter an address or pick below",
  mapReady: "OpenStreetMap / MapLibre ready",
  chooseFromMap: "Choose from map",
  mapCopy: "Pick a suggested North Shore place now. This panel can host a MapLibre map when native map tiles are added.",
  description: "Description",
  descriptionPlaceholder: "What should people expect?",
  backupPrefix: "Backup",
  save: "Create Meetup",
  verificationRequiredTitle: "Profile details need review",
  verificationRequiredCopy:
    "This local prototype asks creators to review basic profile details before saving a real-world meetup idea.",
  reviewSettings: "Review settings",
  verificationTitle: "Review your details",
  verificationCopy:
    "Before creating a real-world plan, review the basic profile details shown in this prototype.",
  displayName: "Name",
  suburb: "Local area",
  age: "Age confirmation",
  photo: "Profile photo",
  contact: "Contact status",
  transport: "Arrival method",
  ageConfirmed: "18 or older confirmed",
  ageMissing: "Needs confirmation",
  photoAdded: "Photo added",
  photoMissing: "Can be added later",
  confirmDetails: "Review in profile",
  editProfile: "Edit Profile",
  close: "Close",
  noise: { Quiet: "Quiet", Balanced: "Balanced", Lively: "Lively" },
} as const;
