export type SydneyRegion =
  | "Sydney CBD"
  | "Eastern Suburbs"
  | "Inner West"
  | "Northern Beaches"
  | "North Shore"
  | "Western Sydney"
  | "South-Western Sydney"
  | "Sutherland Shire"
  | "Greater Sydney";

export type SydneyLocalityKind = "Suburb" | "Region";

export type SydneyLocality = {
  id: string;
  displayName: string;
  region: SydneyRegion;
  kind: SydneyLocalityKind;
  latitude: number;
  longitude: number;
  aliases?: string[];
};

export const officialSydneySuburbNames = [
  "Abbotsbury",
  "Abbotsford",
  "Acacia Gardens",
  "Agnes Banks",
  "Airds",
  "Alexandria",
  "Alfords Point",
  "Allambie Heights",
  "Allawah",
  "Ambarvale",
  "Angus",
  "Annandale",
  "Annangrove",
  "Arcadia",
  "Arncliffe",
  "Arndell Park",
  "Artarmon",
  "Ashbury",
  "Ashcroft",
  "Ashfield",
  "Asquith",
  "Auburn",
  "Austral",
  "Avalon Beach",
  "Badgerys Creek",
  "Balgowlah",
  "Balgowlah Heights",
  "Balmain",
  "Balmain East",
  "Bangor",
  "Banksia",
  "Banksmeadow",
  "Bankstown",
  "Bankstown Aerodrome",
  "Barangaroo",
  "Barden Ridge",
  "Bardia",
  "Bardwell Park",
  "Bardwell Valley",
  "Bass Hill",
  "Baulkham Hills",
  "Bayview",
  "Beacon Hill",
  "Beaconsfield",
  "Beaumont Hills",
  "Beecroft",
  "Belfield",
  "Bella Vista",
  "Bellevue Hill",
  "Belmore",
  "Belrose",
  "Berala",
  "Berkshire Park",
  "Berowra",
  "Berowra Heights",
  "Berowra Waters",
  "Berrilee",
  "Beverley Park",
  "Beverly Hills",
  "Bexley",
  "Bexley North",
  "Bidwill",
  "Bilgola Beach",
  "Bilgola Plateau",
  "Birchgrove",
  "Birrong",
  "Blackett",
  "Blacktown",
  "Blair Athol",
  "Blairmount",
  "Blakehurst",
  "Bligh Park",
  "Bondi",
  "Bondi Beach",
  "Bondi Junction",
  "Bonnet Bay",
  "Bonnyrigg",
  "Bonnyrigg Heights",
  "Bossley Park",
  "Botany",
  "Bow Bowing",
  "Box Hill",
  "Bradbury",
  "Bradfield",
  "Breakfast Point",
  "Brighton-Le-Sands",
  "Bringelly",
  "Bronte",
  "Brooklyn",
  "Brookvale",
  "Bundeena",
  "Bungarribee",
  "Burraneer",
  "Burwood",
  "Burwood Heights",
  "Busby",
  "Cabarita",
  "Cabramatta",
  "Cabramatta West",
  "Caddens",
  "Cambridge Gardens",
  "Cambridge Park",
  "Camellia",
  "Cammeray",
  "Campbelltown",
  "Camperdown",
  "Campsie",
  "Canada Bay",
  "Canley Heights",
  "Canley Vale",
  "Canoelands",
  "Canterbury",
  "Caringbah",
  "Caringbah South",
  "Carlingford",
  "Carlton",
  "Carnes Hill",
  "Carramar",
  "Carss Park",
  "Cartwright",
  "Castle Cove",
  "Castle Hill",
  "Castlecrag",
  "Castlereagh",
  "Casula",
  "Catherine Field",
  "Cattai",
  "Cecil Hills",
  "Cecil Park",
  "Centennial Park",
  "Chatswood",
  "Chatswood West",
  "Cheltenham",
  "Cherrybrook",
  "Chester Hill",
  "Chifley",
  "Chippendale",
  "Chipping Norton",
  "Chiswick",
  "Chullora",
  "Church Point",
  "Claremont Meadows",
  "Clarendon",
  "Clareville",
  "Claymore",
  "Clemton Park",
  "Clontarf",
  "Clovelly",
  "Clyde",
  "Coasters Retreat",
  "Cobbitty",
  "Colebee",
  "Collaroy",
  "Collaroy Plateau",
  "Colyton",
  "Como",
  "Concord",
  "Concord West",
  "Condell Park",
  "Connells Point",
  "Constitution Hill",
  "Coogee",
  "Cottage Point",
  "Cowan",
  "Cranebrook",
  "Cremorne",
  "Cremorne Point",
  "Cromer",
  "Cronulla",
  "Crows Nest",
  "Croydon",
  "Croydon Park",
  "Curl Curl",
  "Currans Hill",
  "Currawong Beach",
  "Daceyville",
  "Dangar Island",
  "Darling Point",
  "Darlinghurst",
  "Darlington",
  "Davidson",
  "Dawes Point",
  "Dean Park",
  "Dee Why",
  "Denham Court",
  "Denistone",
  "Denistone East",
  "Denistone West",
  "Dharruk",
  "Dolans Bay",
  "Dolls Point",
  "Doonside",
  "Double Bay",
  "Dover Heights",
  "Drummoyne",
  "Duffys Forest",
  "Dulwich Hill",
  "Dundas",
  "Dundas Valley",
  "Dural",
  "Eagle Vale",
  "Earlwood",
  "East Hills",
  "East Killara",
  "East Lindfield",
  "East Ryde",
  "Eastern Creek",
  "Eastgardens",
  "Eastlakes",
  "Eastwood",
  "Edensor Park",
  "Edgecliff",
  "Edmondson Park",
  "Elanora Heights",
  "Elderslie",
  "Elizabeth Bay",
  "Elizabeth Hills",
  "Elvina Bay",
  "Emerton",
  "Enfield",
  "Engadine",
  "Englorie Park",
  "Enmore",
  "Epping",
  "Ermington",
  "Erskine Park",
  "Erskineville",
  "Eschol Park",
  "Eveleigh",
  "Fairfield",
  "Fairfield East",
  "Fairfield Heights",
  "Fairfield West",
  "Fairlight",
  "Fiddletown",
  "Five Dock",
  "Forest Glen",
  "Forest Lodge",
  "Forestville",
  "Frenchs Forest",
  "Freshwater",
  "Gables",
  "Galston",
  "Georges Hall",
  "Gilead",
  "Girraween",
  "Gladesville",
  "Glebe",
  "Gledswood Hills",
  "Glen Alpine",
  "Glendenning",
  "Glenfield",
  "Glenhaven",
  "Glenmore Park",
  "Glenorie",
  "Glenwood",
  "Gordon",
  "Grantham Farm",
  "Granville",
  "Grays Point",
  "Great Mackerel Beach",
  "Green Valley",
  "Greenacre",
  "Greendale",
  "Greenfield Park",
  "Greenhills Beach",
  "Greenwich",
  "Gregory Hills",
  "Greystanes",
  "Guildford",
  "Guildford West",
  "Gymea",
  "Gymea Bay",
  "Haberfield",
  "Hammondville",
  "Harrington Park",
  "Harris Park",
  "Hassall Grove",
  "Haymarket",
  "Heathcote",
  "Hebersham",
  "Heckenberg",
  "Henley",
  "Hillsdale",
  "Hinchinbrook",
  "Hobartville",
  "Holroyd",
  "Holsworthy",
  "Homebush",
  "Homebush West",
  "Horningsea Park",
  "Hornsby",
  "Hornsby Heights",
  "Horsley Park",
  "Hoxton Park",
  "Hunters Hill",
  "Huntingwood",
  "Huntleys Cove",
  "Huntleys Point",
  "Hurlstone Park",
  "Hurstville",
  "Hurstville Grove",
  "Illawong",
  "Ingleburn",
  "Ingleside",
  "Jamisontown",
  "Jannali",
  "Jordan Springs",
  "Kangaroo Point",
  "Kareela",
  "Kearns",
  "Kellyville",
  "Kellyville Ridge",
  "Kemps Creek",
  "Kensington",
  "Kenthurst",
  "Kentlyn",
  "Killara",
  "Killarney Heights",
  "Kings Langley",
  "Kings Park",
  "Kingsford",
  "Kingsgrove",
  "Kingswood",
  "Kirkham",
  "Kirrawee",
  "Kirribilli",
  "Kogarah",
  "Kogarah Bay",
  "Ku-ring-gai Chase",
  "Kurnell",
  "Kurraba Point",
  "Kyeemagh",
  "Kyle Bay",
  "La Perouse",
  "Lakemba",
  "Lalor Park",
  "Lane Cove",
  "Lane Cove North",
  "Lane Cove West",
  "Lansdowne",
  "Lansvale",
  "Laughtondale",
  "Lavender Bay",
  "Leets Vale",
  "Leichhardt",
  "Len Waters Estate",
  "Leppington",
  "Lethbridge Park",
  "Leumeah",
  "Lewisham",
  "Liberty Grove",
  "Lidcombe",
  "Lilli Pilli",
  "Lilyfield",
  "Lindfield",
  "Linley Point",
  "Little Bay",
  "Liverpool",
  "Llandilo",
  "Loftus",
  "Londonderry",
  "Long Point",
  "Longueville",
  "Lovett Bay",
  "Lower Portland",
  "Lucas Heights",
  "Luddenham",
  "Lugarno",
  "Lurnea",
  "Macquarie Fields",
  "Macquarie Links",
  "Macquarie Park",
  "Maianbar",
  "Malabar",
  "Manly",
  "Manly Vale",
  "Maraylya",
  "Marayong",
  "Maroota",
  "Maroubra",
  "Marrickville",
  "Marsden Park",
  "Marsfield",
  "Mascot",
  "Matraville",
  "Mays Hill",
  "McCarrs Creek",
  "McGraths Hill",
  "McMahons Point",
  "Meadowbank",
  "Melonba",
  "Melrose Park",
  "Menai",
  "Menangle Park",
  "Merrylands",
  "Merrylands West",
  "Middle Cove",
  "Middle Dural",
  "Middleton Grange",
  "Miller",
  "Millers Point",
  "Milperra",
  "Milsons Passage",
  "Milsons Point",
  "Minchinbury",
  "Minto",
  "Minto Heights",
  "Miranda",
  "Mona Vale",
  "Monterey",
  "Moore Park",
  "Moorebank",
  "Morning Bay",
  "Mortdale",
  "Mortlake",
  "Mosman",
  "Mount Annan",
  "Mount Colah",
  "Mount Druitt",
  "Mount Kuring-Gai",
  "Mount Lewis",
  "Mount Pritchard",
  "Mount Vernon",
  "Mulgoa",
  "Mulgrave",
  "Narellan",
  "Narellan Vale",
  "Naremburn",
  "Narrabeen",
  "Narraweena",
  "Narwee",
  "Nelson",
  "Neutral Bay",
  "Newington",
  "Newport",
  "Newtown",
  "Nirimba Fields",
  "Normanhurst",
  "North Balgowlah",
  "North Bondi",
  "North Curl Curl",
  "North Epping",
  "North Kellyville",
  "North Manly",
  "North Narrabeen",
  "North Parramatta",
  "North Rocks",
  "North Ryde",
  "North St Marys",
  "North Strathfield",
  "North Sydney",
  "North Turramurra",
  "North Wahroonga",
  "North Willoughby",
  "Northbridge",
  "Northmead",
  "Northwood",
  "Norwest",
  "Oakhurst",
  "Oakville",
  "Oatlands",
  "Oatley",
  "Old Guildford",
  "Old Toongabbie",
  "Oran Park",
  "Orchard Hills",
  "Oxford Falls",
  "Oxley Park",
  "Oyster Bay",
  "Paddington",
  "Padstow",
  "Padstow Heights",
  "Pagewood",
  "Palm Beach",
  "Panania",
  "Parklea",
  "Parramatta",
  "Peakhurst",
  "Peakhurst Heights",
  "Pemulwuy",
  "Pendle Hill",
  "Pennant Hills",
  "Penrith",
  "Penshurst",
  "Petersham",
  "Phillip Bay",
  "Picnic Point",
  "Pitt Town",
  "Pleasure Point",
  "Plumpton",
  "Point Piper",
  "Port Botany",
  "Port Hacking",
  "Potts Hill",
  "Potts Point",
  "Prairiewood",
  "Prestons",
  "Prospect",
  "Punchbowl",
  "Putney",
  "Pymble",
  "Pyrmont",
  "Quakers Hill",
  "Queens Park",
  "Queenscliff",
  "Raby",
  "Ramsgate",
  "Ramsgate Beach",
  "Randwick",
  "Redfern",
  "Regents Park",
  "Regentville",
  "Revesby",
  "Revesby Heights",
  "Rhodes",
  "Richards",
  "Richmond",
  "Riverstone",
  "Riverview",
  "Riverwood",
  "Rockdale",
  "Rodd Point",
  "Rookwood",
  "Rooty Hill",
  "Ropes Crossing",
  "Rose Bay",
  "Rosebery",
  "Rosehill",
  "Roselands",
  "Rosemeadow",
  "Roseville",
  "Roseville Chase",
  "Rossmore",
  "Rouse Hill",
  "Rozelle",
  "Ruse",
  "Rushcutters Bay",
  "Russell Lea",
  "Rydalmere",
  "Ryde",
  "Sackville North",
  "Sadleir",
  "Sandringham",
  "Sandy Point",
  "Sans Souci",
  "Schofields",
  "Scotland Island",
  "Seaforth",
  "Sefton",
  "Seven Hills",
  "Shalvey",
  "Shanes Park",
  "Silverwater",
  "Singletons Mill",
  "Smeaton Grange",
  "Smithfield",
  "South Coogee",
  "South Granville",
  "South Hurstville",
  "South Maroota",
  "South Penrith",
  "South Turramurra",
  "South Wentworthville",
  "South Windsor",
  "Spring Farm",
  "St Andrews",
  "St Clair",
  "St Helens Park",
  "St Ives",
  "St Ives Chase",
  "St Johns Park",
  "St Leonards",
  "St Marys",
  "St Peters",
  "Stanhope Gardens",
  "Stanmore",
  "Strathfield",
  "Strathfield South",
  "Summer Hill",
  "Surry Hills",
  "Sutherland",
  "Sydenham",
  "Sydney",
  "Sydney Olympic Park",
  "Sylvania",
  "Sylvania Waters",
  "Tallawong",
  "Tamarama",
  "Taren Point",
  "Telopea",
  "Tempe",
  "Tennyson Point",
  "Terrey Hills",
  "The Ponds",
  "The Rocks",
  "Thornleigh",
  "Toongabbie",
  "Tregear",
  "Turramurra",
  "Turrella",
  "Ultimo",
  "Varroville",
  "Vaucluse",
  "Villawood",
  "Vineyard",
  "Voyager Point",
  "Wahroonga",
  "Waitara",
  "Wakeley",
  "Wareemba",
  "Warrawee",
  "Warriewood",
  "Warwick Farm",
  "Waterfall",
  "Waterloo",
  "Watsons Bay",
  "Wattle Grove",
  "Waverley",
  "Waverton",
  "Wedderburn",
  "Wentworth Point",
  "Wentworthville",
  "Werrington",
  "Werrington County",
  "Werrington Downs",
  "West Hoxton",
  "West Pennant Hills",
  "West Pymble",
  "West Ryde",
  "Westleigh",
  "Westmead",
  "Wetherill Park",
  "Whalan",
  "Whale Beach",
  "Wheeler Heights",
  "Wiley Park",
  "Willmot",
  "Willoughby",
  "Willoughby East",
  "Windsor",
  "Windsor Downs",
  "Winston Hills",
  "Wisemans Ferry",
  "Wolli Creek",
  "Wollstonecraft",
  "Woodbine",
  "Woodcroft",
  "Woodpark",
  "Woollahra",
  "Woolloomooloo",
  "Woolooware",
  "Woolwich",
  "Woronora",
  "Woronora Heights",
  "Yagoona",
  "Yarrawarrah",
  "Yennora",
  "Yowie Bay",
  "Zetland",
] as const;

const slugifySydneyLocality = (name: string) =>
  name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

// Featured prototype entries keep more specific regions and coordinates. The
// official-name fallback below expands search coverage without implying precise
// geocoding for every suburb.
const featuredSydneyLocalities: SydneyLocality[] = [
  { id: "region-sydney-cbd", displayName: "Sydney CBD", region: "Sydney CBD", kind: "Region", latitude: -33.8688, longitude: 151.2093, aliases: ["CBD", "City", "Sydney city"] },
  { id: "region-eastern-suburbs", displayName: "Eastern Suburbs", region: "Eastern Suburbs", kind: "Region", latitude: -33.8915, longitude: 151.2509, aliases: ["East", "Eastern Sydney"] },
  { id: "region-inner-west", displayName: "Inner West", region: "Inner West", kind: "Region", latitude: -33.8899, longitude: 151.1648, aliases: ["Innerwest"] },
  { id: "region-northern-beaches", displayName: "Northern Beaches", region: "Northern Beaches", kind: "Region", latitude: -33.7545, longitude: 151.2876, aliases: ["Beaches", "Northern Sydney beaches"] },
  { id: "region-north-shore", displayName: "North Shore", region: "North Shore", kind: "Region", latitude: -33.75, longitude: 151.15, aliases: ["Upper North Shore", "Lower North Shore"] },
  { id: "region-western-sydney", displayName: "Western Sydney", region: "Western Sydney", kind: "Region", latitude: -33.8144, longitude: 150.9993, aliases: ["West Sydney", "West"] },
  { id: "region-south-western-sydney", displayName: "South-Western Sydney", region: "South-Western Sydney", kind: "Region", latitude: -33.9196, longitude: 150.9254, aliases: ["South West", "Southwestern Sydney"] },
  { id: "region-sutherland-shire", displayName: "Sutherland Shire", region: "Sutherland Shire", kind: "Region", latitude: -34.0353, longitude: 151.0577, aliases: ["The Shire", "Shire"] },
  { id: "sydney-cbd", displayName: "Sydney CBD", region: "Sydney CBD", kind: "Suburb", latitude: -33.8688, longitude: 151.2093, aliases: ["CBD", "City", "Town Hall", "Circular Quay", "Wynyard"] },
  { id: "haymarket", displayName: "Haymarket", region: "Sydney CBD", kind: "Suburb", latitude: -33.8806, longitude: 151.2058, aliases: ["Chinatown"] },
  { id: "surry-hills", displayName: "Surry Hills", region: "Sydney CBD", kind: "Suburb", latitude: -33.8846, longitude: 151.212, aliases: ["Surry"] },
  { id: "bondi", displayName: "Bondi", region: "Eastern Suburbs", kind: "Suburb", latitude: -33.8915, longitude: 151.2657, aliases: ["Bondi Beach"] },
  { id: "randwick", displayName: "Randwick", region: "Eastern Suburbs", kind: "Suburb", latitude: -33.9147, longitude: 151.2418 },
  { id: "newtown", displayName: "Newtown", region: "Inner West", kind: "Suburb", latitude: -33.8984, longitude: 151.1775 },
  { id: "marrickville", displayName: "Marrickville", region: "Inner West", kind: "Suburb", latitude: -33.911, longitude: 151.155 },
  { id: "strathfield", displayName: "Strathfield", region: "Inner West", kind: "Suburb", latitude: -33.8795, longitude: 151.0843 },
  { id: "parramatta", displayName: "Parramatta", region: "Western Sydney", kind: "Suburb", latitude: -33.8144, longitude: 151.0011, aliases: ["Parra"] },
  { id: "blacktown", displayName: "Blacktown", region: "Western Sydney", kind: "Suburb", latitude: -33.771, longitude: 150.9063 },
  { id: "liverpool", displayName: "Liverpool", region: "South-Western Sydney", kind: "Suburb", latitude: -33.9209, longitude: 150.9231 },
  { id: "bankstown", displayName: "Bankstown", region: "South-Western Sydney", kind: "Suburb", latitude: -33.9173, longitude: 151.0359 },
  { id: "cronulla", displayName: "Cronulla", region: "Sutherland Shire", kind: "Suburb", latitude: -34.0575, longitude: 151.1529 },
  { id: "miranda", displayName: "Miranda", region: "Sutherland Shire", kind: "Suburb", latitude: -34.0348, longitude: 151.1007 },
  { id: "manly", displayName: "Manly", region: "Northern Beaches", kind: "Suburb", latitude: -33.7969, longitude: 151.2855 },
  { id: "dee-why", displayName: "Dee Why", region: "Northern Beaches", kind: "Suburb", latitude: -33.7539, longitude: 151.2855 },
  { id: "brookvale", displayName: "Brookvale", region: "Northern Beaches", kind: "Suburb", latitude: -33.7615, longitude: 151.2743 },
  { id: "chatswood", displayName: "Chatswood", region: "North Shore", kind: "Suburb", latitude: -33.7969, longitude: 151.1833 },
  { id: "st-ives", displayName: "St Ives", region: "North Shore", kind: "Suburb", latitude: -33.7291, longitude: 151.1593, aliases: ["St. Ives", "Saint Ives"] },
  { id: "hornsby", displayName: "Hornsby", region: "North Shore", kind: "Suburb", latitude: -33.7039, longitude: 151.0997 },
  { id: "turramurra", displayName: "Turramurra", region: "North Shore", kind: "Suburb", latitude: -33.7314, longitude: 151.1287 },
  { id: "pymble", displayName: "Pymble", region: "North Shore", kind: "Suburb", latitude: -33.7434, longitude: 151.1417 },
  { id: "west-pymble", displayName: "West Pymble", region: "North Shore", kind: "Suburb", latitude: -33.7669, longitude: 151.1285 },
  { id: "gordon", displayName: "Gordon", region: "North Shore", kind: "Suburb", latitude: -33.7569, longitude: 151.1517 },
  { id: "killara", displayName: "Killara", region: "North Shore", kind: "Suburb", latitude: -33.7666, longitude: 151.1622 },
  { id: "lindfield", displayName: "Lindfield", region: "North Shore", kind: "Suburb", latitude: -33.7756, longitude: 151.1689 },
  { id: "roseville", displayName: "Roseville", region: "North Shore", kind: "Suburb", latitude: -33.7841, longitude: 151.1783 },
  { id: "artarmon", displayName: "Artarmon", region: "North Shore", kind: "Suburb", latitude: -33.8088, longitude: 151.1844 },
  { id: "lane-cove", displayName: "Lane Cove", region: "North Shore", kind: "Suburb", latitude: -33.8152, longitude: 151.1667 },
  { id: "north-sydney", displayName: "North Sydney", region: "North Shore", kind: "Suburb", latitude: -33.839, longitude: 151.2071 },
  { id: "crows-nest", displayName: "Crows Nest", region: "North Shore", kind: "Suburb", latitude: -33.8258, longitude: 151.2016 },
  { id: "neutral-bay", displayName: "Neutral Bay", region: "North Shore", kind: "Suburb", latitude: -33.8319, longitude: 151.219 },
  { id: "mosman", displayName: "Mosman", region: "North Shore", kind: "Suburb", latitude: -33.8276, longitude: 151.2446 },
  { id: "wahroonga", displayName: "Wahroonga", region: "North Shore", kind: "Suburb", latitude: -33.7181, longitude: 151.1156 },
  { id: "waitara", displayName: "Waitara", region: "North Shore", kind: "Suburb", latitude: -33.7105, longitude: 151.103 },
  { id: "asquith", displayName: "Asquith", region: "North Shore", kind: "Suburb", latitude: -33.6879, longitude: 151.1086 },
  { id: "thornleigh", displayName: "Thornleigh", region: "North Shore", kind: "Suburb", latitude: -33.7312, longitude: 151.0789 },
  { id: "pennant-hills", displayName: "Pennant Hills", region: "North Shore", kind: "Suburb", latitude: -33.7378, longitude: 151.0732 },
  { id: "epping", displayName: "Epping", region: "North Shore", kind: "Suburb", latitude: -33.7727, longitude: 151.0818 },
  { id: "macquarie-park", displayName: "Macquarie Park", region: "North Shore", kind: "Suburb", latitude: -33.7756, longitude: 151.1179, aliases: ["Macquarie"] },
  { id: "ryde", displayName: "Ryde", region: "North Shore", kind: "Suburb", latitude: -33.8136, longitude: 151.1066 },
];

const featuredSydneyLocalityNames = new Set(featuredSydneyLocalities.map((locality) => locality.displayName));

const officialSydneySuburbFallbacks: SydneyLocality[] = officialSydneySuburbNames
  .filter((name) => !featuredSydneyLocalityNames.has(name))
  .map((name) => ({
    id: `official-${slugifySydneyLocality(name)}`,
    displayName: name,
    region: "Greater Sydney",
    kind: "Suburb",
    latitude: -33.8688,
    longitude: 151.2093,
  }));

export const sydneyLocalities: SydneyLocality[] = [
  ...featuredSydneyLocalities,
  ...officialSydneySuburbFallbacks,
];
