import type {
  AvailabilityTimingPreference,
  DatingStylePreference,
  FriendshipStylePreference,
  LocationComfortPreference,
  LifeComfortPreference,
  MeetupContactPreference,
  MeetupRhythmPreference,
  SocialDurationPreference,
  TransportationMethod,
  TransportationPreference,
} from "../app-settings";

export type PreferenceOptionDetail<T extends string> = {
  value: T;
  icon: string;
  copy: string;
  group?: string;
};

export const transportationPreferenceDetails: PreferenceOptionDetail<TransportationPreference>[] = [
  { value: "Walking", icon: "🚶", copy: "Nearby meetups and clear walking directions feel easiest.", group: "Transport method" },
  { value: "Public transport", icon: "🚆", copy: "Train, metro, bus, ferry, or light rail access helps.", group: "Transport method" },
  { value: "Train", icon: "🚆", copy: "Meetups near train stations are preferred.", group: "Transport method" },
  { value: "Metro", icon: "🚇", copy: "Metro access makes the plan easier.", group: "Transport method" },
  { value: "Bus", icon: "🚌", copy: "Bus-friendly meeting points are useful.", group: "Transport method" },
  { value: "Ferry", icon: "⛴️", copy: "Ferry access is comfortable for some local plans.", group: "Transport method" },
  { value: "Light rail", icon: "🚈", copy: "Light rail access helps where available.", group: "Transport method" },
  { value: "Driving", icon: "🚗", copy: "Driving is okay if the meeting point is clear.", group: "Transport method" },
  { value: "Parking needed", icon: "🅿️", copy: "Parking details make meetups feel easier.", group: "Transport method" },
  { value: "Rideshare / taxi", icon: "🚕", copy: "Pickup and drop-off friendly locations help.", group: "Transport method" },
  { value: "Cycling", icon: "🚲", copy: "Bike-friendly routes and lock-up spots matter.", group: "Transport method" },
  { value: "Carpool okay", icon: "🤝", copy: "Carpooling could be okay when trust and logistics are clear.", group: "Transport method" },
  { value: "Prefer nearby only", icon: "📍", copy: "Nearby plans feel more comfortable.", group: "Travel comfort" },
  { value: "Avoid long travel", icon: "🧭", copy: "Long trips can make meetups feel less easy.", group: "Travel comfort" },
  { value: "Step-free / accessible routes preferred", icon: "♿", copy: "Step-free and accessible routes are preferred where possible.", group: "Travel comfort" },
  { value: "Short trips only", icon: "⏱️", copy: "Short travel windows are best.", group: "Travel comfort" },
  { value: "Comfortable travelling at night", icon: "🌙", copy: "Evening travel can feel okay with clear plans.", group: "Travel comfort" },
  { value: "Prefer daytime travel", icon: "☀️", copy: "Daytime travel feels easier.", group: "Travel comfort" },
  { value: "Prefer well-lit routes", icon: "💡", copy: "Well-lit routes and meeting points are preferred.", group: "Travel comfort" },
  { value: "Prefer close to public transport", icon: "🚉", copy: "A short walk from transport helps.", group: "Travel comfort" },
];

export const meetupContactPreferenceDetails: PreferenceOptionDetail<MeetupContactPreference>[] = [
  { value: "In-app chat", icon: "💬", copy: "Keep coordination inside the app prototype.", group: "Communication style" },
  { value: "Details only", icon: "📝", copy: "Key details without lots of extra chat.", group: "Communication style" },
  { value: "Low-message mode", icon: "🔕", copy: "Fewer messages and less pressure.", group: "Communication style" },
  { value: "Chat before meetup", icon: "💬", copy: "A short chat beforehand can help.", group: "Communication style" },
  { value: "Group chat okay", icon: "👥", copy: "Group meetup chat feels okay.", group: "Communication style" },
  { value: "Direct messages okay", icon: "✉️", copy: "Direct messages are okay when relevant.", group: "Communication style" },
  { value: "Voice call okay", icon: "📞", copy: "A short voice call can be okay.", group: "Communication style" },
  { value: "No voice calls", icon: "🚫", copy: "Text-based planning is preferred.", group: "Communication style" },
  { value: "Reminders only", icon: "⏰", copy: "Just the essential reminders.", group: "Communication style" },
  { value: "Prefer clear plans", icon: "✅", copy: "Clear time, place, and plan details help.", group: "Communication style" },
  { value: "Prefer short messages", icon: "↔️", copy: "Short practical messages feel easiest.", group: "Communication style" },
  { value: "Okay with check-ins", icon: "🛟", copy: "Gentle check-ins are okay around the meetup.", group: "Communication style" },
  { value: "Slow replies are okay", icon: "🌿", copy: "No need for instant replies.", group: "Timing and pace" },
  { value: "Reply when I can", icon: "🕊️", copy: "Replies happen when there is time and energy.", group: "Timing and pace" },
  { value: "Same-day messages okay", icon: "📅", copy: "Same-day coordination is okay.", group: "Timing and pace" },
  { value: "Prefer planning ahead", icon: "🗓️", copy: "Advance notice makes plans easier.", group: "Timing and pace" },
  { value: "Last-minute plans okay", icon: "⚡", copy: "Short-notice plans can be okay.", group: "Timing and pace" },
  { value: "No pressure to reply quickly", icon: "🌿", copy: "Keep message expectations low-pressure.", group: "Timing and pace" },
];

export const locationComfortPreferenceDetails: PreferenceOptionDetail<LocationComfortPreference>[] = [
  { value: "Near my selected suburb", icon: "📍", copy: "Meetups near your selected suburb feel easiest.", group: "Area comfort" },
  { value: "North Shore preferred", icon: "🌉", copy: "North Shore plans are preferred.", group: "Area comfort" },
  { value: "Sydney CBD okay", icon: "🏙️", copy: "Sydney CBD meetups can be okay.", group: "Area comfort" },
  { value: "Northern Beaches okay", icon: "🌊", copy: "Northern Beaches plans can be okay.", group: "Area comfort" },
  { value: "Inner West okay", icon: "🚆", copy: "Inner West plans can be okay.", group: "Area comfort" },
  { value: "Close to public transport", icon: "🚉", copy: "Transport-adjacent venues feel easier.", group: "Venue comfort" },
  { value: "Parking nearby", icon: "🅿️", copy: "Nearby parking helps.", group: "Venue comfort" },
  { value: "Indoor venues", icon: "🏠", copy: "Indoor venues feel comfortable.", group: "Venue comfort" },
  { value: "Outdoor venues", icon: "🌳", copy: "Parks, walks, and outdoor venues feel comfortable.", group: "Venue comfort" },
  { value: "Quiet venues", icon: "🌿", copy: "Lower-noise venues are preferred.", group: "Venue comfort" },
  { value: "Well-lit areas", icon: "💡", copy: "Well-lit locations are preferred.", group: "Venue comfort" },
  { value: "Familiar places", icon: "🧭", copy: "Familiar public places feel easier.", group: "Venue comfort" },
  { value: "Easy exit / easy to leave", icon: "🚪", copy: "Simple arrival and exit paths matter.", group: "Venue comfort" },
  { value: "Avoid crowded venues", icon: "👥", copy: "Lower-crowd plans feel better.", group: "Venue comfort" },
  { value: "Avoid loud bars", icon: "🔕", copy: "Loud bar settings are not preferred.", group: "Venue comfort" },
  { value: "Prefer smoke-free venues", icon: "🌬️", copy: "Smoke-free spaces feel more comfortable.", group: "Smoke & air comfort" },
  { value: "Sensitive to cigarette smoke", icon: "🌬️", copy: "Cigarette smoke can make a venue uncomfortable.", group: "Smoke & air comfort" },
  { value: "Sensitive to vape smoke", icon: "🌬️", copy: "Vape smoke can make a venue uncomfortable.", group: "Smoke & air comfort" },
  { value: "Outdoor smoking okay", icon: "🌳", copy: "Outdoor smoking nearby can be okay when it is separate from the meetup.", group: "Smoke & air comfort" },
  { value: "Prefer fresh-air/open venues", icon: "🍃", copy: "Fresh-air or open venues feel easier.", group: "Smoke & air comfort" },
  { value: "Smoke-free meetup preferred", icon: "🌿", copy: "A smoke-free meetup plan is preferred.", group: "Smoke & air comfort" },
  { value: "Sensitive to strong perfumes/colognes", icon: "🌿", copy: "Strong perfumes or colognes can feel uncomfortable.", group: "Fragrance & scent comfort" },
  { value: "Prefer low-scent environments", icon: "🍃", copy: "Low-scent spaces feel easier.", group: "Fragrance & scent comfort" },
  { value: "Mild fragrances okay", icon: "🌿", copy: "Mild fragrances are usually okay.", group: "Fragrance & scent comfort" },
  { value: "Strong fragrances uncomfortable", icon: "🌬️", copy: "Strong scent levels can make meetups harder.", group: "Fragrance & scent comfort" },
  { value: "Prefer fresh-air spaces", icon: "🍃", copy: "Fresh-air spaces can make scent levels easier.", group: "Fragrance & scent comfort" },
  { value: "Prefer lighter conversation first", icon: "💬", copy: "Starting with lighter conversation can feel easier.", group: "Conversation comfort" },
  { value: "Okay discussing deeper topics later", icon: "🌱", copy: "Deeper topics may be okay after some trust and context.", group: "Conversation comfort" },
  { value: "Prefer avoiding politics initially", icon: "🕊️", copy: "Political topics are best avoided early unless the group has agreed otherwise.", group: "Conversation comfort" },
  { value: "Prefer avoiding religion debates", icon: "🕊️", copy: "Debates about religion are best avoided unless the event is clearly for that kind of discussion.", group: "Conversation comfort" },
  { value: "Avoid personal questioning early on", icon: "🔒", copy: "Personal questions should wait until trust and comfort build.", group: "Conversation comfort" },
  { value: "Prefer gradual trust-building", icon: "🌿", copy: "Trust can build slowly through repeated ease and respect.", group: "Conversation comfort" },
  { value: "Sensitive to sarcasm-heavy humour", icon: "💬", copy: "Sarcasm-heavy humour can feel uncomfortable or hard to read.", group: "Conversation comfort" },
  { value: "Prefer calmer humour", icon: "🌿", copy: "Gentler humour feels easier.", group: "Conversation comfort" },
  { value: "Comfortable with playful banter", icon: "✨", copy: "Playful banter can be okay when it stays kind and mutual.", group: "Conversation comfort" },
  { value: "Prefer respectful language", icon: "🤝", copy: "Respectful language helps the meetup feel easier.", group: "Conversation comfort" },
  { value: "Family-friendly tone preferred", icon: "👪", copy: "A family-friendly tone is preferred.", group: "Conversation comfort" },
  { value: "Quiet/shared-activity focused", icon: "🎲", copy: "Shared activity can carry the meetup without needing constant conversation.", group: "Conversation comfort" },
  { value: "Debate-friendly (optional/specialized events only)", icon: "💬", copy: "Debate works best only for events that clearly invite it.", group: "Conversation comfort" },
  { value: "Prefer calmer language", icon: "💬", copy: "Calmer wording and tone feel easiest.", group: "Conversation comfort" },
  { value: "Family-friendly language preferred", icon: "💬", copy: "Family-friendly language is preferred.", group: "Conversation comfort" },
  { value: "Okay with casual swearing", icon: "💬", copy: "Casual swearing can be okay in relaxed conversation.", group: "Conversation comfort" },
  { value: "Prefer lower-intensity conversations", icon: "🌿", copy: "Lower-intensity conversations feel easier.", group: "Conversation comfort" },
  { value: "Comfortable with expressive/social energy", icon: "✨", copy: "Expressive social energy can feel okay.", group: "Conversation comfort" },
  { value: "Calm atmosphere", icon: "🌿", copy: "The meetup tone is calm and steady.", group: "Meetup tone labels" },
  { value: "Light/social conversation", icon: "💬", copy: "Light social conversation is welcome without pressure to go deep.", group: "Meetup tone labels" },
  { value: "Deeper discussion welcome", icon: "🌱", copy: "Deeper discussion can be welcome when people opt into it.", group: "Meetup tone labels" },
  { value: "Humour-friendly", icon: "✨", copy: "Humour is welcome when it stays respectful and mutual.", group: "Meetup tone labels" },
  { value: "Quiet/shared activity", icon: "🎲", copy: "Conversation can be lighter while the shared activity carries the meetup.", group: "Meetup tone labels" },
  { value: "Family-friendly tone", icon: "👪", copy: "The meetup tone is suitable for family-friendly language and topics.", group: "Meetup tone labels" },
  { value: "Flexible conversation pacing", icon: "🌊", copy: "Conversation can move between quiet, light, and deeper moments.", group: "Meetup tone labels" },
  { value: "Public restroom access", icon: "🚻", copy: "Public restroom access helps with planning.", group: "Venue accessibility & practical comfort" },
  { value: "Step-free access", icon: "♿", copy: "Step-free venue access is preferred.", group: "Venue accessibility & practical comfort" },
  { value: "Seating available", icon: "🪑", copy: "Available seating makes the meetup easier.", group: "Venue accessibility & practical comfort" },
  { value: "Quiet seating areas", icon: "🌿", copy: "Quiet seating areas are helpful.", group: "Venue accessibility & practical comfort" },
  { value: "Nearby transport", icon: "🚉", copy: "Transport close to the venue helps.", group: "Venue accessibility & practical comfort" },
  { value: "Nearby parking", icon: "🅿️", copy: "Parking close to the venue helps.", group: "Venue accessibility & practical comfort" },
  { value: "Indoor backup available", icon: "🏠", copy: "An indoor backup can make weather changes easier.", group: "Venue accessibility & practical comfort" },
  { value: "Water nearby", icon: "💧", copy: "Water access nearby is useful.", group: "Venue accessibility & practical comfort" },
  { value: "Wheelchair-accessible routes", icon: "♿", copy: "Wheelchair-accessible routes are preferred where possible.", group: "Venue accessibility & practical comfort" },
  { value: "Low-noise venue", icon: "🔕", copy: "A low-noise venue is preferred.", group: "Venue accessibility & practical comfort" },
  { value: "Loud environment possible", icon: "🔊", copy: "The meetup may include louder moments, while still giving people context ahead of time.", group: "Loud environment guidance" },
  { value: "Bring earbuds/headphones if helpful", icon: "🎧", copy: "Earbuds or headphones may help for people who use them in louder settings.", group: "Loud environment guidance" },
  { value: "Noise-sensitive friendly", icon: "🌿", copy: "The plan should leave room for people who prefer lower sensory load.", group: "Loud environment guidance" },
  { value: "Quiet recharge nearby", icon: "🌿", copy: "A quieter nearby place or pause point would help.", group: "Loud environment guidance" },
  { value: "Lower-noise alternative nearby", icon: "🔕", copy: "A calmer nearby option can make energetic events easier to try.", group: "Loud environment guidance" },
  { value: "Accessibility details coming later", icon: "🛠️", copy: "A placeholder for clearer venue accessibility notes in a later pass.", group: "Venue accessibility & practical comfort" },
  { value: "Prefer daytime locations", icon: "☀️", copy: "Daytime plans feel easier.", group: "Time comfort" },
  { value: "Comfortable with evening locations", icon: "🌙", copy: "Evening locations can be okay with clear plans.", group: "Time comfort" },
  { value: "Do not show exact location", icon: "🔒", copy: "Avoid sharing exact places or routines.", group: "Location privacy" },
  { value: "Share suburb only", icon: "📍", copy: "Suburb-level sharing is enough.", group: "Location privacy" },
  { value: "Share region only", icon: "🗺️", copy: "Region-level sharing is preferred.", group: "Location privacy" },
  { value: "Ask before sharing location", icon: "❔", copy: "Ask before sharing more location context.", group: "Location privacy" },
];

export const friendshipStylePreferenceDetails: PreferenceOptionDetail<FriendshipStylePreference>[] = [
  { value: "Casual friendships", icon: "🌿", copy: "Light, easy friendship without needing every meetup to feel deep." },
  { value: "Deeper friendships", icon: "🤝", copy: "Open to friendships that become more emotionally steady over time." },
  { value: "Activity-based friendships", icon: "🎲", copy: "Shared activities first, with conversation growing naturally." },
  { value: "Small trusted circle", icon: "🛡️", copy: "A smaller circle can feel more comfortable than many loose connections." },
  { value: "Open to gradual connection", icon: "🕰️", copy: "Connection can build slowly without pressure to decide quickly." },
  { value: "Conversation-focused", icon: "💬", copy: "Conversation is a meaningful part of friendship." },
  { value: "Shared hobbies first", icon: "🎨", copy: "Hobbies and interests can make connection feel easier." },
];

export const datingStylePreferenceDetails: PreferenceOptionDetail<DatingStylePreference>[] = [
  { value: "Friendship-first dating", icon: "🤝", copy: "Friendship and ease matter before romantic expectations." },
  { value: "Slow-burn connection", icon: "🌙", copy: "Romantic interest can unfold gradually." },
  { value: "Casual dating", icon: "☕", copy: "Open to casual dating without pressure to define everything quickly." },
  { value: "Long-term relationship open", icon: "🌱", copy: "Open to something long-term if it develops naturally." },
  { value: "Exploring without pressure", icon: "🧭", copy: "Still figuring out dating preferences without a strict goal." },
  { value: "Prefer getting to know people slowly", icon: "🕰️", copy: "Slow, respectful pacing feels best." },
];

export const meetupRhythmPreferenceDetails: PreferenceOptionDetail<MeetupRhythmPreference>[] = [
  { value: "One-time meetup", icon: "📍", copy: "A single meetup is okay without assuming a repeat plan.", group: "Meetup rhythm & consistency" },
  { value: "Weekly", icon: "📅", copy: "A weekly rhythm can feel comfortable when energy allows.", group: "Meetup rhythm & consistency" },
  { value: "Fortnightly", icon: "🗓️", copy: "Every couple of weeks may feel easier to sustain.", group: "Meetup rhythm & consistency" },
  { value: "Monthly", icon: "🌙", copy: "Monthly plans can keep connection gentle and manageable.", group: "Meetup rhythm & consistency" },
  { value: "Occasional/random", icon: "🌊", copy: "Irregular plans are okay when life is variable.", group: "Meetup rhythm & consistency" },
  { value: "Seasonal/special events", icon: "✨", copy: "Special events or seasonal meetups may be enough.", group: "Meetup rhythm & consistency" },
];

export const availabilityTimingPreferenceDetails: PreferenceOptionDetail<AvailabilityTimingPreference>[] = [
  { value: "Weekdays", icon: "📅", copy: "Weekday plans can work.", group: "Availability & timing" },
  { value: "Weekends", icon: "🗓️", copy: "Weekend plans are easiest.", group: "Availability & timing" },
  { value: "Daytime", icon: "☀️", copy: "Daytime meetups feel comfortable.", group: "Availability & timing" },
  { value: "Evenings", icon: "🌙", copy: "Evening meetups can work with clear plans.", group: "Availability & timing" },
  { value: "Late-night friendly", icon: "🌃", copy: "Later plans can be okay when the venue and transport are clear.", group: "Availability & timing" },
  { value: "Flexible schedule", icon: "🌿", copy: "Timing can vary and stay flexible.", group: "Availability & timing" },
];

export const socialDurationPreferenceDetails: PreferenceOptionDetail<SocialDurationPreference>[] = [
  { value: "Quick meetup (30-45 mins)", icon: "⏱️", copy: "Short meetups can feel easier to try.", group: "Social duration comfort" },
  { value: "About an hour", icon: "🕐", copy: "Around an hour feels like a comfortable default.", group: "Social duration comfort" },
  { value: "1-2 hours", icon: "🕑", copy: "A medium-length meetup can work.", group: "Social duration comfort" },
  { value: "Several hours okay", icon: "🕓", copy: "Longer plans can be okay when energy and setting feel right.", group: "Social duration comfort" },
  { value: "Half-day outing", icon: "🧭", copy: "A longer outing can be comfortable for some plans.", group: "Social duration comfort" },
  { value: "Flexible timing", icon: "🌊", copy: "Timing can adapt to the group and the day.", group: "Social duration comfort" },
  { value: "Leave anytime", icon: "🚪", copy: "Leaving early should stay normal and low-pressure.", group: "Social duration comfort" },
];

export const lifeComfortPreferenceDetails: PreferenceOptionDetail<LifeComfortPreference>[] = [
  { value: "Approaching people can feel hard", icon: "🌿", copy: "Gentle context for meetups where first contact may take a little time.", group: "Social comfort & life pacing" },
  { value: "I warm up slowly socially", icon: "🌿", copy: "Starting quietly or observing first can feel easier.", group: "Social comfort & life pacing" },
  { value: "Large groups can feel overwhelming", icon: "👥", copy: "Smaller subgroups or clear step-out options may help.", group: "Social comfort & life pacing" },
  { value: "Sleep schedules can vary", icon: "🕰️", copy: "Timing flexibility may make plans easier.", group: "Things that can feel difficult sometimes" },
  { value: "Motivation can fluctuate", icon: "🌊", copy: "Gentle planning and easy opt-in choices can help.", group: "Things that can feel difficult sometimes" },
  { value: "Exercise consistency can be difficult", icon: "🚶", copy: "Movement plans should stay low-pressure and adjustable.", group: "Things that can feel difficult sometimes" },
  { value: "I recharge alone sometimes", icon: "🕯️", copy: "Time alone after or between social plans can be useful.", group: "Things I'm working through" },
  { value: "Busy/noisy places can feel draining", icon: "🔕", copy: "Lower-noise options or a quiet pause can help.", group: "Things I'm working through" },
  { value: "I overthink social situations sometimes", icon: "💬", copy: "Clear, kind expectations can make social plans feel easier.", group: "Things I'm working through" },
  { value: "I prefer gentle pacing", icon: "🌿", copy: "Slower, optional participation is preferred.", group: "Social comfort & life pacing" },
  { value: "Prefer not to say", icon: "🔒", copy: "Skip this section entirely.", group: "Social comfort & life pacing" },
];

export const transportationMethodByPreference: Partial<Record<TransportationPreference, TransportationMethod>> = {
  Walking: "Walking",
  "Public transport": "Public transport",
  Train: "Public transport",
  Metro: "Public transport",
  Bus: "Public transport",
  Ferry: "Public transport",
  "Light rail": "Public transport",
  Driving: "Driving",
  "Parking needed": "Driving",
  "Rideshare / taxi": "Rideshare",
  Cycling: "Cycling",
};
